stan-core:
  stanPath: .stan
  excludes: 
    - '**/.tsbuild/**'
    - '**/*.tsbuildinfo'
    - CHANGELOG.md
    - package-lock.json
stan-cli:
  cliDefaults:
    run:
      facets: false
      plan: false
      sequential: true
  patchOpenCommand: code -g {file}
  scripts:
    lint: npm run lint
